version: "3.8"
services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app  
      - yarn-volume:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/site_colmeia_development
    depends_on:
      - postgres
    tty: true
    stdin_open: true

  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  yarn-volume:
  dbdata: